from dataclasses import dataclass

# pasts, currents, nexts 

@dataclass
class Templates:
    keywords = [
        "Interact and sing",
        "Interview",
        "Rock paper scissors",
        "Cook instruction",
        "Sarcasm",
        "Talk jokes",
        "Math",
        "Math teaching",
        "Learn English",
        "Learn Chinese",
        "Meeting",
        "Online meeting",
        "Translation",
        "Real-time translation",
        "Lullaby",
        "Celebrate",
        "Interact with pet",
        "Jokes",
        "Dad jokes",
        "City introduction",
        "Customer service proof of concept",
        "Talk",
        "Phone talk",
        "Vlog",
        "Talking friends",
        "Visual puzzle",
        "Paint",
        "Paint instruction",
        "Video reaction",
        "Tidy desktop",
        "Google Glass",
        "GPT-4",
        "Gemini",
        "AI assistant",
        "VisionPro",
        "Live",
        "Egocentric",
        "AI demo",
        "AI agent",
        "Robot",
        "Boston Dynamics",
        "GoPro",
        "Personalized AI",
        "Text writing",
        "Course",
        "Instruction",
        "Real-time interaction",
        "Cooking tutorial",
        "Fitness workout",
        "Home workout",
        "Meditation guide",
        "Travel vlog",
        "Adventure travel",
        "Tech review",
        "Gadget unboxing",
        "DIY crafts",
        "Home decor",
        "Makeup tutorial",
        "Skincare routine",
        "Fashion haul",
        "Outfit ideas",
        "Book review",
        "Movie review",
        "Gaming highlights",
        "Let's play",
        "Game walkthrough",
        "Music cover",
        "Instrumental music",
        "Live concert",
        "Study tips",
        "Career advice",
        "Job interview tips",
        "Resume writing",
        "Freelancing tips",
        "Coding tutorial",
        "Web development",
        "Data science",
        "Stock market",
        "Investing tips",
        "Personal finance",
        "Budgeting tips",
        "Parenting advice",
        "Baby care",
        "Pet care",
        "Gardening tips",
        "Plant care",
        "Sustainable living",
        "Productivity hacks",
        "Time management",
        "Goal setting",
        "Personal development",
        "Public speaking",
        "Networking tips",
        "Motivation speech",
        "Confidence building",
        "Leadership skills",
        "Team building",
        "Project management",
        "Entrepreneurship",
        "Small business tips",
        "Side hustle",
        "Productivity tools",
        "Digital marketing",
        "Social media strategy",
        "Content creation",
        "Podcasting tips",
        "Voiceover techniques",
        "Storytelling",
        "Presentation skills",
        "Creative writing",
        "Poetry reading",
        "Songwriting tips",
        "Singing lessons",
        "Music theory",
        "Art critique",
        "Drawing tutorial",
        "Photography tips",
        "Video editing",
        "Animation tutorial",
        "Graphic design",
        "Interior design",
        "Architecture",
        "Real estate tips",
        "Home renovation",
        "Lifestyle vlog",
        "Minimalism",
        "Healthy eating",
        "Recipe sharing",
        "Food review",
        "Wine tasting",
        "Restaurant review",
        "Travel guide",
        "Historical tour",
        "Cultural exploration",
        "Language learning tips",
        "Exam preparation",
        "Study abroad",
        "Volunteer work",
        "Charity events",
        "Community service",
        "Fashion tips",
        "Hairstyling",
        "Beard grooming",
        "Nail art",
        "Healthy recipes",
        "Vegan cooking",
        "Paleo diet",
        "Keto diet",
        "Cooking hacks",
        "Baking tutorial",
        "Dessert recipes",
        "Cocktail making",
        "Coffee brewing",
        "Tea tasting",
        "Fitness tips",
        "Yoga practice",
        "Pilates workout",
        "Dance tutorial",
        "Zumba class",
        "Martial arts",
        "Boxing training",
        "CrossFit workout",
        "Marathon training",
        "Hiking guide",
        "Cycling tips",
        "Mountain biking",
        "Surfing tutorial",
        "Skateboarding tricks",
        "Snowboarding guide",
        "Skiing tips",
        "Rock climbing",
        "Scuba diving",
        "Snorkeling guide",
        "Fishing tips",
        "Hunting guide",
        "Camping tips",
        "RV living",
        "Van life",
        "Car maintenance",
        "DIY repairs",
        "Woodworking",
        "Metalworking",
        "Blacksmithing",
        "Knife making",
        "Pottery making",
        "Glassblowing",
        "Calligraphy",
        "Origami",
        "Sewing tutorial",
        "Knitting patterns",
        "Crocheting tips",
        "Quilting",
        "Embroidery",
        "Candle making",
        "Soap making",
        "Perfume making",
        "Makeup hacks",
        "Skincare tips",
        "Beauty routines",
        "Fashion DIY",
        "Mindfulness",
        "Stress management",
        "Mental health tips",
        "Therapy advice",
        "Relationship advice",
        "Dating tips",
        "Marriage counseling",
        "Divorce support",
        "Family therapy",
        "Child psychology",
        "Teen advice",
        "Life coaching",
        "Career coaching",
        "Retirement planning",
        "Estate planning",
        "Insurance tips",
        "Credit repair",
        "Debt management",
        "Financial freedom",
        "Passive income",
        "Real estate investment",
        "Property management",
        "House flipping",
        "Rental property tips",
        "Urban gardening",
        "Hydroponics",
        "Permaculture",
        "Organic farming",
        "Homesteading",
        "Survival skills",
        "Prepping tips",
        "Self-defense",
        "Gun safety",
        "Archery tips",
        "Outdoor survival",
        "Wilderness survival",
        "Bushcraft",
        "Foraging",
        "Herbal remedies",
        "Natural medicine",
        "Acupuncture",
        "Chiropractic care",
        "Physical therapy",
        "Occupational therapy",
        "Speech therapy",
        "Autism support",
        "ADHD management",
        "Dyslexia help",
        "Learning disabilities",
        "Special education",
        "Classroom management",
        "Lesson planning",
        "Teacher training",
        "Homeschooling tips",
        "Montessori method",
        "Waldorf education",
        "Reggio Emilia approach",
        "Unschooling",
        "E-learning",
        "Online courses",
        "MOOC reviews",
        "Language exchange",
        "Pronunciation tips",
        "Accent reduction",
        "Public relations",
        "Crisis management",
        "Media training",
        "Press release tips",
        "Brand building",
        "Influencer marketing",
        "Affiliate marketing",
        "Email marketing",
        "SEO tips",
        "PPC advertising",
        "Content marketing",
        "Blogging tips",
        "Website design",
        "UX design",
        "UI design",
        "App development",
        "Mobile development",
        "Game design",
        "Game development",
        "Virtual reality",
        "Augmented reality",
        "Blockchain technology",
        "Cryptocurrency",
        "NFT guide",
        "Smart home tech",
        "Home automation",
        "Internet of Things",
        "Cybersecurity",
        "Ethical hacking",
        "Data privacy",
        "Cloud computing",
        "Artificial intelligence",
        "Machine learning",
        "Robotics",
        "Drone flying",
        "3D printing",
        "Voice acting",
        "Audiobook narration",
        "Broadcasting tips",
        "Radio hosting",
        "TV presenting",
        "News reporting",
        "Journalism tips",
        "Investigative reporting",
        "Editorial writing",
        "Opinion pieces",
        "Debate skills",
        "Argumentation techniques",
        "Critical thinking",
        "Logical reasoning",
        "Cognitive biases",
        "Persuasion techniques",
        "Negotiation skills",
        "Conflict resolution",
        "Mediation tips",
        "Public relations crisis",
        "Corporate communications",
        "Internal communications",
        "Employee engagement",
        "Team motivation",
        "Organizational culture",
        "Change management",
        "Innovation strategies",
        "Business strategy",
        "Market research",
        "Competitive analysis",
        "Product development",
        "Product management",
        "Customer experience",
        "User research",
        "Customer journey mapping",
        "Consumer behavior",
        "Retail strategies",
        "E-commerce tips",
        "Online retail",
        "Dropshipping",
        "Wholesale business",
        "Supply chain management",
        "Logistics tips",
        "Inventory management",
        "Procurement tips",
        "Vendor management",
        "Quality control",
        "Lean manufacturing",
        "Six Sigma",
        "Agile methodologies",
        "Scrum framework",
        "Kanban system",
        "Project scheduling",
        "Risk management",
        "Cost estimation",
        "Resource allocation",
        "Stakeholder management",
        "Performance metrics",
        "KPI tracking",
        "Business analytics",
        "Data visualization",
        "Data mining",
        "Big data",
        "Predictive analytics",
        "Business intelligence",
        "Financial modeling",
        "Valuation techniques",
        "Corporate finance",
        "Investment banking",
        "Private equity",
        "Venture capital",
        "Crowdfunding",
        "Startup advice",
        "Pitching to investors",
        "Business incubation",
        "Accelerators",
        "Corporate innovation",
        "Tech startups",
        "Fintech",
        "Healthtech",
        "Edtech",
        "Biotech",
        "Greentech",
        "Renewable energy",
        "Solar energy",
        "Wind power",
        "Electric vehicles",
        "Smart cities",
        "Urban planning",
        "Sustainable architecture",
        "Green building",
        "Energy efficiency",
        "Water conservation",
        "Waste management",
        "Recycling tips",
        "Zero waste lifestyle",
        "Climate change",
        "Environmental activism",
        "Wildlife conservation",
        "Marine conservation"
    ]
